config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'games#home'
  get 'new', to: 'games#new'
  post 'score', to: 'games#score'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
require 'open-uri'
require 'json'

class GamesController < ApplicationController
  def new
    @letters = ('A'..'Z').to_a.sample(10).join
  end

  def score
    @user_input = params[:input]
    @word = params[:letters]
    @include = include?(@word, @user_input)
    @english_word = english_word?(@user_input)
  end

  def home
  end

  private

  def include?(user_input, letters)
    user_input.chars.all? do |letter|
      user_input.count(letter) <= letters.count(letter)
    end
  end

  def english_word?(word)
    file_open = URI.open("https://wagon-dictionary.herokuapp.com/#{word}")
    file_json = JSON.parse(file_open.read)
    file_json['found']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/home.html.erb
<h1>********* Welcome to the longest word-game! *********</h1>
<%= link_to "Start game!", new_path, class: "btn btn-primary" %>

app/views/games/new.html.erb
<h2>New game</h2>
  <p> Here is your grid: </p>
  <%= @letters %>
    <br><br>
<form action="/score" method="post" data-turbo="false">
  <p> What is your longest word? </p>
  <input type="text" class="user-input" name="input">
  <input type="submit" class="submit btn btn-primary" value="Play">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <%= hidden_field_tag :letters, @letters %>
</form>

app/views/games/score.html.erb
<div class="container m-2 p-2">
  <h2>******** Now your results ********</h2>
  <h3>Result</h3>
  <% finish = Time.now %>

  <% if @included %>
    <% if @english_word %>
      <p><strong>Congratulations!</strong> <%= @user_input %> is a valid English word!</p>
      <p>Your time was <strong><%="#{(Time.now - Time.at(@start_time.to_i)).round(2)}"%></strong> seconds</p>
      <p>Your word has <%=@user_input.length%> letters! </p>
      <p>You scored <%=(@user_input.length/(Time.now - Time.at(@start_time.to_i))*10).round(2)%> points.</p>
      <%= link_to "Go back to the Home page", home_path %>
    <% else %>
      <p>Sorry but <strong><%= @user_input %></strong> does not seem to be a valid English word...</p>
      <%= link_to "Try again.", new_path %>
    <% end %>
  <% else %>
    <p>Sorry but <strong><%= @user_input %></strong> can't be built out of <%= @word %></p>
    <%= link_to "Try again.", new_path %>
  <% end %>
</div>

  <%# <% if @word.empty? %>
    <%# <%=  "Congratulations! #{@user_input} is valid word!" %>
    <%# <%= link_to "Play again!", new_path %>
  <%# <% elsif @include == false %>
    <%# <%= "Sorry. I can't build a word with #{@user_input}." %>
    <%# <%= link_to "Play again!", new_path %>
  <%# <% elsif @english_word == false %>
    <%# <%= "Sorry. #{@user_input} is not a english word." %>
    <%# <%= link_to "Play again!", new_path %>
  <%# <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>